config/routes.rb
Rails.application.routes.draw do
  root to: 'shops#index'

  resources :shops
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ApplicationRecord
  validates :chain, :name, :address, :city, presence: true
  validates :latitude , numericality: { greater_than_or_equal_to:  -90, less_than_or_equal_to:  90 }
  validates :longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }
  validates :phone, format: { with: /(\(\+33\)|0|\+33|0033)[1-9]([0-9]{8}|([0-9\- ]){12})/ }

  geocoded_by :full_address
  # after_validation :geocode, if: :address_changed_and_lat_long_nil?


  def full_address
    [address, city].compact.join(', ')
  end

  # private

  # def address_changed_and_lat_long_nil?
  #   (latitude.nil? || longitude.nil?) && address_changed?
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search].present? #search name/city form

      sql_search = "name ILIKE :search OR city ILIKE :search"
      @shops = Shop.where(sql_search, search: "%#{params[:search]}%")

      @hash = Gmaps4rails.build_markers(@shops) do |shop, marker|
          marker.lat shop.latitude
          marker.lng shop.longitude
          marker.infowindow render_to_string(partial: "/shops/map_box", locals: { shop: shop })
      end
      respond_to do |format|
        format.html { render 'shops/index' }
        format.js
      end

    elsif params[:distance].present? #search distance form

      @shops = Shop.near(params[:location], params[:distance])
      @hash = Gmaps4rails.build_markers(@shops) do |shop, marker|
          marker.lat shop.latitude
          marker.lng shop.longitude
          marker.infowindow render_to_string(partial: "/shops/map_box", locals: { shop: shop })
      end
      respond_to do |format|
        format.html { render 'shops/index' }
        format.js
      end

    else

      @shops = Shop.where.not(latitude: nil, longitude: nil)
      @hash = Gmaps4rails.build_markers(@shops) do |shop, marker|
          marker.lat shop.latitude
          marker.lng shop.longitude
          marker.infowindow render_to_string(partial: "/shops/map_box", locals: { shop: shop })
      end
      respond_to do |format|
        format.html { render 'shops/index' }
        format.js
      end

    end

  end


  def show
    @hash = Gmaps4rails.build_markers(@shop) do |shop, marker|
        marker.lat shop.latitude
        marker.lng shop.longitude
        marker.infowindow render_to_string(partial: "/shops/map_box", locals: { shop: shop })
    end
  end

  def new
    @shop = Shop.new
  end

  def create

    @shop = Shop.new(shop_params)
    if (@shop.latitude.nil? || @shop.longitude.nil?) && @shop.address_changed?
      @shop.geocode
    end
    if @shop.save
      redirect_to shop_path(@shop)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @shop.update(shop_params)
      redirect_to shop_path(@shop)
    else
      render :edit
    end
  end

  def destroy
    @shop.destroy
    redirect_to shops_path
  end

  private

  def shop_params
    params.require(:shop).permit(:chain, :name, :latitude, :longitude, :address, :city, :phone, :zip, :country_code)
  end

  def set_shop
    @shop = Shop.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.0.0/css/bootstrap-slider.css" />
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_SERVER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.0.0/bootstrap-slider.js" %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="navbar-shopmium">

    <%= link_to 'Home', shops_path, class: 'navbar-shopmium-item navbar-shopmium-link' %>


    <%= form_tag(shops_path, method: :get, remote: true, class: "navbar-shopmium-search text-center") do %>
      <%= text_field_tag :search, params[:search], class: "navbar-shopmium-search-input", placeholder: "Chercher un shop" %>
      <button type="submit" class="navbar-shopmium-search-btn">
        <i class="fa fa-search"></i>
      </button>
    <% end %>

    <%= link_to 'Ajouter un shop', new_shop_path, class: 'navbar-shopmium-item navbar-shopmium-link' %>

</div>

app/views/shops/_form.html.erb
<%= simple_form_for(shop) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :chain %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :city %>
      <%= f.input :zip %>
      <%= f.input :phone %>
      <%= f.input :country_code, as: :string %>
    </div>

    <div class="form-actions">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>

app/views/shops/_map.html.erb
<div id="map" style="width: 100%; height: 70vh;" data-markers="<%= markers.to_json %>"></div>

<% content_for(:after_js) do %>
  <script>
    const handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map' } }, function() {
      if(navigator.geolocation){
        navigator.geolocation.getCurrentPosition(displayOnMap,error);
      }

      function error(error) {
        $("input[type='hidden']").remove();
        $('#distanceform').prepend("<input id='location' name='location' value=''>");
        $('#distanceform').prepend("<label for='location'>Location:</label>");
      };

      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });


    function displayOnMap(position){
      const lat = position.coords.latitude
      const lng = position.coords.longitude
      coords = lat + ',' + lng
      $('input[name="location"]').val(coords)

      const marker = handler.addMarker({
        lat: position.coords.latitude,
        lng: position.coords.longitude,
        picture: {
          url: "http://maps.google.com/mapfiles/ms/icons/blue-dot.png",
          width:  36,
          height: 36
        },

      });
      handler.bounds.extendWith(marker);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      // send(coords);
    };

    // function send(coords){
    //   $.ajax({
    //     url : "<%= shops_path %>",
    //     type : "get",
    //     contentType: "json",
    //     data: { coords: coords },
    //   })
    // };



  </script>
<% end %>

app/views/shops/_map_box.html.erb
<h4> <%= link_to shop.name, shop_path(shop)  %> </h4>
<p><%= shop.address %> - <%= shop.city %> - <%= shop.zip %></p>
<p><%= shop.phone %></p>

app/views/shops/_shops.html.erb
<% @shops.each do |shop| %>
  <div class="product">
  <div class='product-body'>
    <h3><%= shop.name %></h3>
    <p><%= shop.city %></p>
  </div>
  <ul class="list-inline product-controls hidden-sm hidden-xs">
    <li><%= link_to shop_path(shop) do %>
      <i class="fa fa-eye"></i>
    <% end %></li>
    <li><%= link_to edit_shop_path(shop) do %>
      <i class="fa fa-pencil"></i>
    <% end %></li>
    <li><%= link_to shop_path(shop), method: :delete do %><i class="fa fa-trash-o"></i>
    <% end %></li>
  </ul>
</div>
<% end %>

app/views/shops/edit.html.erb
<div class="form-container">

  <h2 class="text-center">Edit shop</h2>

  <%= render 'form', shop: @shop %>


</div>

app/views/shops/index.html.erb
<!-- <h1>Tous les shops</h1> -->
<div class="flex">
  <div class="search-form">
    <%= form_tag(shops_path, method: :get, id: "distanceform" ) do %>
      <input id="hidden" type="hidden" name="location" value="" >
      <%= label :distance, "Distance : " %>
      <span>0</span><input id="ex1" data-slider-id='ex1Slider' name="distance" type="text" data-slider-min="0" data-slider-max="100" data-slider-step="1" data-slider-value= "" /><span>1000 mètres</span>

      <%= submit_tag "Search", class: "btn-gray" %>
    <% end %>
  </div>
</div>

<div class="padded">
  <div class="row">

    <div class="col-xs-6">
      <div id="shops">
        <%= render 'shops', shops: @shops %>
      </div>
    </div>

     <div class="col-xs-6">
      <div id="map_google">
        <%= render 'map', markers: @markers %>
      </div>

    </div>

  </div>
</div>

<%= content_for(:after_js) do %>
  <script>
    <% if params[:distance] %>
      const distanceValue = <%= raw params[:distance] %>
    <% else %>
      const distanceValue = 0
    <% end %>

    const mySlider = new Slider('#ex1', {
      value: distanceValue,
      tooltip: 'always',
      formatter: function(value) {
        return value * 100;
      }
    });

  </script>
<% end %>

app/views/shops/index.js.erb
$(document).ready(function(){

  $('#shops').html("<%= escape_javascript(render("shops")) %>")
  $('#map_google').html("<%= escape_javascript(render("map")) %>")

});

app/views/shops/new.html.erb
<div class="form-container">

  <h2>Add shop</h2>

  <%= render 'form', shop: @shop %>


</div>

app/views/shops/show.html.erb
<div
  id="map"
  style="width: 100%;
  height: 50vh;"
  data-markers="<%= @markers.to_json %>"
></div>

<div class="flex title">
  <div class="name"><%= @shop.name %></div>
  <div class="link">
    <%= link_to edit_shop_path(@shop) do %>
      <i class="fa fa-pencil"></i>
    <% end %>
    <%= link_to shop_path(@shop), method: :delete do %>
      <i class="fa fa-trash-o"></i>
    <% end %>
  </div>
</div>

<div class="flex-vertical infos">
  <div class="chain"><%= @shop.chain.capitalize %></div>
  <div>
    <i class="fa fa-map-marker"></i>
    <%= @shop.full_address %> -
    <%= @shop.zip %>
  </div>
  <div>
    <i class="fa fa-phone"></i>
    <%= @shop.phone %>
  </div>
</div>


<% content_for(:after_js) do %>
  <script>
    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map' } }, function() {
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(14);
      }
    });
  </script>
<% end %>